version: '3.8'

services:
  backend:
    container_name: backend
    # image: hr9457/backend_practica1_201314296
    build: ./Backend_node
    restart: always
    environment:
      HOSTDB : "192.168.187.131"
      PORTDB : 3306
      DBNAME : "proyecto"
      USERDB : "root"
      PASSDB : "root"          

    ports:
      - "5000:5000"
    # depends_on:
    #   - mysql

    networks:
      - practica1


  frontend:
    container_name: frontend
    build: ./frontend
    # image: hr9457/frontend_practica1_201314296
    restart: always
    environment:
      REACT_APP_API_URL : "http://localhost:5000"

    ports:
      - "3000:3000"

    depends_on:
      - backend

    networks:
      - practica1


networks:
  practica1:
    name: practica1
    driver: bridge